# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11GYYg0rLdpjE6oaRFJ-ruxaXcCm3yQL-

# Dependencies
"""

import subprocess
import sys

# Install required packages
subprocess.check_call([sys.executable, "-m", "pip", "install", "streamlit", "transformers", "torch", "deepface", "opencv-python", "mediapipe"])

import streamlit as st
import cv2
from deepface import DeepFace
from transformers import pipeline
import numpy as np

"""# Initialize Models"""

@st.cache_resource
def load_sentiment_model():
  return pipeline('sentiment-analysis')

sentiment_model = load_sentiment_model()

"""## Facial Emotion Detection"""

def detect_facial_emotion(frame):
  try:
    analysis = DeepFace.analyze(frame, actions=['emotion'], enforce_detection=False)
    return analysis['dominant_emotion']
  except Exception as e:
    return 'Error: Unable to detect emotion.'

"""# Text Sentiment Analysis"""

def detect_text_emotion(text):
  result = sentiment_model(text)
  if result:
    return result[0]['label'], result[0]['score']
    return 'Neutral', 0.0

"""# Streamlit App"""

st.title('Real-Time Mood Detection')

"""## Sidebar for Text Sentiment Analysis"""

st.sidebar.header('Text Sentiment Analysis')
user_text = st.sidebar.text_area('Enter your text:', 'I am feeling happy today!')

if user_text:
  text_emotion, text_score = detect_text_emotion(user_text)
  st.sidebar.write(f'Detected Sentiment: {text_emotion} (Score: {text_score: .2f})')

"""## Webcam for Facial Emotion Detection"""

st.header('Facial Emotion Detection')
run_camera = st.button('Start Camera')

if run_camera:
  st.write('Press "q" to stop the webcam.')
  cap = cv2.VideoCapture(0)

  while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
      break

    # Flip the frame for a natural mirror-like experience
    frame = cv2.flip(frame, 1)

    # Detect emotion
    emotion = detect_facial_emotion(frame)

    #Display result on frame
    cv2,putText(frame, f'Emotion: {emotion}', (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    cv2.imshow('Facial Emotion Detection', frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
      break

  cap.release()
  cv2.destroyAllWindown()

st.header('Summary')
if user_text:
  st.write(f'Text Emotion: {text_emotion} (Score: {text_score:.2f})')

if run_camera:
    st.write("Facial emotion detection is displayed on the webcam feed.")
    st.write("Facial emotion detection is displayed on the webcam feed.")